### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ejstembler** [ankane/breakout-ruby#2]
Hi, thanks for releasing this!  I didn't see a discussions tab, so I'm posting my question here.

I have a series with 2,590 entries.  It consists of a UTC time and an integer value. Something like this:

```ruby
require 'time'
require 'breakout-detection'

series = {
  Time.parse('2021-09-22T11:58:37Z') => 301590765,
  Time.parse('2021-09-22T12:05:15Z') => 9421127680,
  Time.parse('2021-09-22T12:25:32Z') => 301590765,
  # ...
}

results = Breakout.detect(series)
# results=[]
```

Most of the values are in the range of `300,000,000`, however, one value is `9,421,127,680`.  Should the breakout detect the 9 million value?  Currently, it's returning an empty array.

Am I doing something wrong? Should I change a default setting?

Thanks!

**Comment by ankane** [comment]
Hey @ejstembler, the `min_size` option determines the minimum size of a breakout (30 by default). A single anomaly isn't a considered a breakout.

**Comment by ejstembler** [comment]
@ankane Thanks.  I actually found another repo of yours which worked out: [OutlierTree](https://github.com/ankane/outliertree):

```ruby
model = OutlierTree.new
model.fit(data)
results = model.outliers(data)

puts results[:explanation]
# "meters (9421127680) looks high"
```

Thanks for creating these!

**Comment by ankane** [comment]
Great. For time series anomaly detection (which takes into account seasonality and trend), also check out [AnomalyDetection.rb](https://github.com/ankane/AnomalyDetection.rb) (just released).
