### ISSUE TITLE
This example is returning 5 breakouts but I'm expecting 0

### ISSUE THREAD

**Issue by breiko83** [ankane/breakout-ruby#3]
```
series = [0, 0, 0, 0, 0, 0, 0, 2, 5, 45, 50, 60, 80, 80, 80, 90, 100, 110, 100, 90, 80, 50, 10, 0] * 8
now = Time.zone.now.beginning_of_year
time_series = series.map.with_index.to_h { |v, i| [now + i.hour, v] }

breakouts = Breakout.detect(time_series, min_size: 24)
```
![Screenshot 2023-06-16 at 16 51 48](https://github.com/ankane/breakout-ruby/assets/598231/0dcd43ce-1a4d-43f4-89b2-65ba9c35cb1f)

I'm trying to identify breakouts in a 24 hours interval. The current series is repeated 8 times to simulate no breakouts. I would expect Breakout.detect to return 0 breakouts but in fact I receive 5 as result. Any suggestions?

**Comment by ankane** [comment]
Hi @breiko83, you'll probably want to remove seasonality with something like [STL Ruby](https://github.com/ankane/stl-ruby) before passing the series to `Breakout.detect`.

```ruby
seasonal = Stl.decompose(time_series, period: 24)[:seasonal]
time_series = time_series.zip(seasonal).to_h { |(k, v), s| [k, v - s] }
```
